# Terrascan configuration for Lambda Cron Service
[rules]
  # Skip rules that may not apply to containerized lambda functions
  skip-rules = [
    # Add any rules to skip here as needed
  ]

[severity]
  # Set minimum severity level (LOW, MEDIUM, HIGH)
  level = "MEDIUM"