FROM public.ecr.aws/lambda/nodejs:18

# Copy package.json and install dependencies
COPY package.json ./
RUN npm install

# Copy worker source code
COPY worker.js ./

# Set the CMD to your handler
CMD ["worker.handler"]